services:
  glassfish:
    build: .
    container_name: glassfish-server
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8080"  # Mapeia a porta externa para a porta interna 8080
      - "${CONSOLE_PORT}:4848"  # Mapeia a porta do console
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_USER=${ADMIN_USER}
      - AS_ADMIN_USER=${AS_ADMIN_USER}
    volumes:
      - ./apps:/opt/glassfish/glassfish/domains/domain1/autodeploy
      - ./glassfish-config:/opt/glassfish/glassfish/domains/domain1/config
    restart: always
    entrypoint: [ "/usr/local/bin/entrypoint.sh", "start" ]  # Não é necessário se já estiver no Dockerfile
